// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.18.1
// source: nmap_srv/nmap_srv.proto

package nmap_srv

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DeliverScanIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanId string `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
}

func (x *DeliverScanIdReq) Reset() {
	*x = DeliverScanIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nmap_srv_nmap_srv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverScanIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverScanIdReq) ProtoMessage() {}

func (x *DeliverScanIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_nmap_srv_nmap_srv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverScanIdReq.ProtoReflect.Descriptor instead.
func (*DeliverScanIdReq) Descriptor() ([]byte, []int) {
	return file_nmap_srv_nmap_srv_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverScanIdReq) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type DeliverScanIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//响应码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *DeliverScanIdResp) Reset() {
	*x = DeliverScanIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nmap_srv_nmap_srv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverScanIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverScanIdResp) ProtoMessage() {}

func (x *DeliverScanIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_nmap_srv_nmap_srv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverScanIdResp.ProtoReflect.Descriptor instead.
func (*DeliverScanIdResp) Descriptor() ([]byte, []int) {
	return file_nmap_srv_nmap_srv_proto_rawDescGZIP(), []int{1}
}

func (x *DeliverScanIdResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_nmap_srv_nmap_srv_proto protoreflect.FileDescriptor

var file_nmap_srv_nmap_srv_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6e, 0x6d, 0x61, 0x70, 0x5f, 0x73, 0x72, 0x76, 0x2f, 0x6e, 0x6d, 0x61, 0x70, 0x5f,
	0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x6d, 0x61, 0x70, 0x5f,
	0x73, 0x72, 0x76, 0x22, 0x2b, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x53, 0x63,
	0x61, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x63, 0x61, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x61, 0x6e, 0x49, 0x64,
	0x22, 0x27, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x53, 0x63, 0x61, 0x6e, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x55, 0x0a, 0x07, 0x4e, 0x6d, 0x61,
	0x70, 0x53, 0x72, 0x76, 0x12, 0x4a, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x53,
	0x63, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x2e, 0x6e, 0x6d, 0x61, 0x70, 0x5f, 0x73, 0x72, 0x76,
	0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x53, 0x63, 0x61, 0x6e, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x1b, 0x2e, 0x6e, 0x6d, 0x61, 0x70, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x53, 0x63, 0x61, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x42, 0x1c, 0x5a, 0x1a, 0x6e, 0x61, 0x73, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72,
	0x70, 0x63, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6d, 0x61, 0x70, 0x5f, 0x73, 0x72, 0x76, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nmap_srv_nmap_srv_proto_rawDescOnce sync.Once
	file_nmap_srv_nmap_srv_proto_rawDescData = file_nmap_srv_nmap_srv_proto_rawDesc
)

func file_nmap_srv_nmap_srv_proto_rawDescGZIP() []byte {
	file_nmap_srv_nmap_srv_proto_rawDescOnce.Do(func() {
		file_nmap_srv_nmap_srv_proto_rawDescData = protoimpl.X.CompressGZIP(file_nmap_srv_nmap_srv_proto_rawDescData)
	})
	return file_nmap_srv_nmap_srv_proto_rawDescData
}

var file_nmap_srv_nmap_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nmap_srv_nmap_srv_proto_goTypes = []interface{}{
	(*DeliverScanIdReq)(nil),  // 0: nmap_srv.DeliverScanIdReq
	(*DeliverScanIdResp)(nil), // 1: nmap_srv.DeliverScanIdResp
}
var file_nmap_srv_nmap_srv_proto_depIdxs = []int32{
	0, // 0: nmap_srv.NmapSrv.DeliverScanId:input_type -> nmap_srv.DeliverScanIdReq
	1, // 1: nmap_srv.NmapSrv.DeliverScanId:output_type -> nmap_srv.DeliverScanIdResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nmap_srv_nmap_srv_proto_init() }
func file_nmap_srv_nmap_srv_proto_init() {
	if File_nmap_srv_nmap_srv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nmap_srv_nmap_srv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliverScanIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nmap_srv_nmap_srv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliverScanIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nmap_srv_nmap_srv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nmap_srv_nmap_srv_proto_goTypes,
		DependencyIndexes: file_nmap_srv_nmap_srv_proto_depIdxs,
		MessageInfos:      file_nmap_srv_nmap_srv_proto_msgTypes,
	}.Build()
	File_nmap_srv_nmap_srv_proto = out.File
	file_nmap_srv_nmap_srv_proto_rawDesc = nil
	file_nmap_srv_nmap_srv_proto_goTypes = nil
	file_nmap_srv_nmap_srv_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NmapSrvClient is the client API for NmapSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NmapSrvClient interface {
	DeliverScanId(ctx context.Context, in *DeliverScanIdReq, opts ...grpc.CallOption) (*DeliverScanIdResp, error)
}

type nmapSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewNmapSrvClient(cc grpc.ClientConnInterface) NmapSrvClient {
	return &nmapSrvClient{cc}
}

func (c *nmapSrvClient) DeliverScanId(ctx context.Context, in *DeliverScanIdReq, opts ...grpc.CallOption) (*DeliverScanIdResp, error) {
	out := new(DeliverScanIdResp)
	err := c.cc.Invoke(ctx, "/nmap_srv.NmapSrv/DeliverScanId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NmapSrvServer is the server API for NmapSrv service.
type NmapSrvServer interface {
	DeliverScanId(context.Context, *DeliverScanIdReq) (*DeliverScanIdResp, error)
}

// UnimplementedNmapSrvServer can be embedded to have forward compatible implementations.
type UnimplementedNmapSrvServer struct {
}

func (*UnimplementedNmapSrvServer) DeliverScanId(context.Context, *DeliverScanIdReq) (*DeliverScanIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverScanId not implemented")
}

func RegisterNmapSrvServer(s *grpc.Server, srv NmapSrvServer) {
	s.RegisterService(&_NmapSrv_serviceDesc, srv)
}

func _NmapSrv_DeliverScanId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverScanIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NmapSrvServer).DeliverScanId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nmap_srv.NmapSrv/DeliverScanId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NmapSrvServer).DeliverScanId(ctx, req.(*DeliverScanIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _NmapSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nmap_srv.NmapSrv",
	HandlerType: (*NmapSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverScanId",
			Handler:    _NmapSrv_DeliverScanId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nmap_srv/nmap_srv.proto",
}
