definitions:
  formjson.AddUserReq:
    properties:
      confirm:
        description: 确认用户密码
        type: string
      mail:
        description: 用户邮箱
        type: string
      mobile:
        description: 用户手机号码
        type: string
      password:
        description: 用户密码
        type: string
      remark:
        description: 用户备注信息
        type: string
      user_type:
        description: 用户类型
        type: integer
      username:
        description: 用户名
        type: string
    required:
    - confirm
    - password
    - username
    type: object
  formjson.DeleteContextStreamChatReq:
    properties:
      session_id:
        description: session id
        type: integer
    type: object
  formjson.DeleteUserReq:
    properties:
      uids:
        description: 要删除的用户id列表
        items:
          type: integer
        type: array
    required:
    - uids
    type: object
  formjson.EditUserReq:
    properties:
      mail:
        description: 用户邮箱
        type: string
      mobile:
        description: 用户联系方式
        type: string
      uid:
        description: 用户ID
        type: integer
    required:
    - uid
    type: object
  formjson.GenerateImageReq:
    properties:
      model_name:
        description: model name
        type: string
      prompt:
        description: prompt content
        type: string
      quality:
        description: image quality
        type: string
      size:
        description: image size
        type: string
    type: object
  formjson.GenerateImageResp:
    properties:
      base64:
        description: image content
        type: string
    type: object
  formjson.GetUserInfoResp:
    properties:
      create_time:
        description: 创建时间
        type: integer
      email:
        description: 注册邮箱
        type: string
      phone:
        description: 联系手机
        type: string
      ps:
        description: 密码强度(1 低|2 中|3 强)
        type: integer
      uid:
        description: 用户id
        type: integer
      user_type:
        description: 用户角色(1 管理员|2 超级用户|3 普通用户)
        type: integer
      username:
        description: 用户名
        type: string
    type: object
  formjson.ListUserItem:
    properties:
      create_time:
        description: 用h用户创建时间
        type: integer
      enable:
        description: 是否允许登录
        type: boolean
      mail:
        description: 用户邮箱
        type: string
      mobile:
        description: 用户联系方式
        type: string
      uid:
        description: 用户id
        type: integer
      user_type:
        description: 用户类型
        type: integer
      username:
        description: 用户名
        type: string
    type: object
  formjson.ListUserResp:
    properties:
      count:
        description: 总数
        type: integer
      results:
        description: 结果
        items:
          $ref: '#/definitions/formjson.ListUserItem'
        type: array
    type: object
  formjson.LoginReq:
    properties:
      capt_id:
        description: 验证码唯一ID
        type: string
      password:
        description: 用户密码
        type: string
      username:
        description: 用户名称
        type: string
      vcode:
        description: 验证码
        type: string
    required:
    - capt_id
    - password
    - username
    - vcode
    type: object
  formjson.LoginResp:
    properties:
      authorization:
        description: 用于鉴权的token
        type: string
      enable:
        description: 是否允许登陆
        type: boolean
      uid:
        description: 用户Id
        type: integer
      username:
        description: 用户名
        type: string
    type: object
  formjson.ResetPasswdReq:
    properties:
      password:
        description: 重置用户密码
        type: string
      uid:
        description: 用户ID
        type: integer
    required:
    - password
    - uid
    type: object
  formjson.SendContextStreamChatReq:
    properties:
      model_name:
        description: chat model name
        type: string
      question:
        description: chat content
        type: string
      session_id:
        description: session id
        type: integer
    type: object
  formjson.SendNoContextNoStreamChatReq:
    properties:
      model_name:
        description: chat model name
        type: string
      question:
        description: System    string `json:"system"`     // model system content
        type: string
    type: object
  formjson.SendNoContextNoStreamChatResp:
    properties:
      answer:
        description: assistant answer
        type: string
    type: object
  formjson.SendNoContextStreamChatReq:
    properties:
      model_name:
        description: chat model name
        type: string
      question:
        description: chat content
        type: string
    type: object
  formjson.StatusResp:
    properties:
      status:
        description: 基本状态
        type: string
    type: object
  formjson.TranscriptionsResp:
    properties:
      text:
        description: assistant answer
        type: string
    type: object
  formjson.UpdateUserPasswdReq:
    properties:
      new:
        description: 新密码
        type: string
      new2:
        description: 确认新密码
        type: string
      old:
        description: 旧密码
        type: string
      uid:
        description: 用户ID
        type: integer
    type: object
  formjson.UpdateUserStatusReq:
    properties:
      enable:
        description: 是否允许登录
        type: boolean
      uid:
        description: 用户id
        type: integer
    required:
    - uid
    type: object
  formjson.VerifyCodeResp:
    properties:
      capt_id:
        description: 验证码唯一ID
        type: string
      image:
        description: 验证码图片数据
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login/:
    post:
      consumes:
      - application/json
      description: user login
      parameters:
      - description: request data
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/formjson.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.LoginResp'
      security:
      - ApiKeyAuth: []
      summary: 基础接口 - 用户登录
      tags:
      - common
  /auth/logout/:
    post:
      consumes:
      - application/json
      description: user logout
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.StatusResp'
      security:
      - ApiKeyAuth: []
      summary: 基础接口 - 用户登出
      tags:
      - common
  /auth/verifycode/:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: get verifycode
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.VerifyCodeResp'
      security:
      - ApiKeyAuth: []
      summary: 基础接口 - 获取验证码
      tags:
      - common
  /v1/audio/transcriptions:
    post:
      consumes:
      - multipart/form-data
      description: Transcribes audio into the input language
      parameters:
      - description: audio file data
        in: formData
        name: file
        required: true
        type: file
      - description: input audio language [optional]
        in: query
        name: language
        type: string
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.TranscriptionsResp'
      security:
      - ApiKeyAuth: []
      summary: Transcribes audio into the input language
      tags:
      - Audio
  /v1/chat/context_stream:
    post:
      consumes:
      - application/json
      description: send support context stream chat
      parameters:
      - description: request data
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/formjson.SendContextStreamChatReq'
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.StatusResp'
      security:
      - ApiKeyAuth: []
      summary: 发送上下文流式聊天
      tags:
      - Chat
  /v1/chat/delete_context_stream:
    delete:
      consumes:
      - application/json
      description: delete context stream chat
      parameters:
      - description: request data
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/formjson.DeleteContextStreamChatReq'
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.StatusResp'
      security:
      - ApiKeyAuth: []
      summary: 删除上下文流式聊天
      tags:
      - Chat
  /v1/chat/no_context_no_stream:
    post:
      consumes:
      - application/json
      description: send no context no stream chat
      parameters:
      - description: request data
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/formjson.SendNoContextNoStreamChatReq'
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.SendNoContextNoStreamChatResp'
      security:
      - ApiKeyAuth: []
      summary: 发送无上下文无流式聊天
      tags:
      - Chat
  /v1/chat/no_context_stream:
    post:
      consumes:
      - application/json
      description: send no context stream chat
      parameters:
      - description: request data
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/formjson.SendNoContextStreamChatReq'
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.StatusResp'
      security:
      - ApiKeyAuth: []
      summary: 发送无上下文流式聊天
      tags:
      - Chat
  /v1/image/generate:
    post:
      consumes:
      - application/json
      description: generate image by using text
      parameters:
      - description: request data
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/formjson.GenerateImageReq'
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.GenerateImageResp'
      security:
      - ApiKeyAuth: []
      summary: generate image
      tags:
      - Image
  /v1/user/:
    delete:
      consumes:
      - application/json
      description: delete user
      parameters:
      - description: request data
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/formjson.DeleteUserReq'
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.StatusResp'
      security:
      - ApiKeyAuth: []
      summary: 删除用户
      tags:
      - 用户管理
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: list user
      parameters:
      - description: 是否允许登录 [1 允许登录| -1 禁止登录| 0 全部]
        in: query
        name: enable
        type: integer
      - description: 分页
        in: query
        name: page
        type: integer
      - description: 分页大小
        in: query
        name: page_size
        type: integer
      - description: 搜索 [用户名| 邮箱|联系方式]
        in: query
        name: search
        type: string
      - description: 用户类型 [ 1 管理员 | 2 超级用户 | 3 普通用户| 0 全部用户]
        in: query
        name: user_type
        type: integer
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.ListUserResp'
      security:
      - ApiKeyAuth: []
      summary: 获取用户列表
      tags:
      - 用户管理
    post:
      consumes:
      - application/json
      description: add user
      parameters:
      - description: request data
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/formjson.AddUserReq'
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.StatusResp'
      security:
      - ApiKeyAuth: []
      summary: 添加用户
      tags:
      - 用户管理
    put:
      consumes:
      - application/json
      description: edit user
      parameters:
      - description: request data
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/formjson.EditUserReq'
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.StatusResp'
      security:
      - ApiKeyAuth: []
      summary: 编辑用户
      tags:
      - 用户管理
  /v1/user/info:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: get user info
      parameters:
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.GetUserInfoResp'
      security:
      - ApiKeyAuth: []
      summary: 获取当前用户信息
      tags:
      - 用户管理
  /v1/user/passwd/:
    put:
      consumes:
      - application/json
      description: update user password
      parameters:
      - description: request data
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/formjson.UpdateUserPasswdReq'
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.StatusResp'
      security:
      - ApiKeyAuth: []
      summary: 修改用户密码
      tags:
      - 用户管理
  /v1/user/reset_passwd:
    post:
      consumes:
      - application/json
      description: reset user password
      parameters:
      - description: request data
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/formjson.ResetPasswdReq'
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.StatusResp'
      security:
      - ApiKeyAuth: []
      summary: 重置用户密码
      tags:
      - 用户管理
  /v1/user/status/:
    put:
      consumes:
      - application/json
      description: update user login status
      parameters:
      - description: request data
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/formjson.UpdateUserStatusReq'
      - description: authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response data
          schema:
            $ref: '#/definitions/formjson.StatusResp'
      security:
      - ApiKeyAuth: []
      summary: 修改用户登录状态（是否允许登录）
      tags:
      - 用户管理
swagger: "2.0"
