// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.18.1
// source: forward/secgrp_forward.proto

package forward

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Action int32

const (
	Action_ADDRULE         Action = 0
	Action_DELETERULE      Action = 1
	Action_STARTCISCHECK   Action = 2
	Action_RECOVERCISCHECK Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ADDRULE",
		1: "DELETERULE",
		2: "STARTCISCHECK",
		3: "RECOVERCISCHECK",
	}
	Action_value = map[string]int32{
		"ADDRULE":         0,
		"DELETERULE":      1,
		"STARTCISCHECK":   2,
		"RECOVERCISCHECK": 3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_forward_secgrp_forward_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_forward_secgrp_forward_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_forward_secgrp_forward_proto_rawDescGZIP(), []int{0}
}

type ForwardAgentActionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action        Action `protobuf:"varint,1,opt,name=action,proto3,enum=forward.Action" json:"action,omitempty"`                //指令行为
	RuleDirection int32  `protobuf:"varint,2,opt,name=rule_direction,json=ruleDirection,proto3" json:"rule_direction,omitempty"` //规则应用方向 | CIS ID
	ProtocolType  int32  `protobuf:"varint,3,opt,name=protocol_type,json=protocolType,proto3" json:"protocol_type,omitempty"`    //协议类型
	ApplyPolicy   int32  `protobuf:"varint,4,opt,name=apply_policy,json=applyPolicy,proto3" json:"apply_policy,omitempty"`       //授权策略
	Port          string `protobuf:"bytes,5,opt,name=port,proto3" json:"port,omitempty"`                                         //应用端口
	Cidr          string `protobuf:"bytes,6,opt,name=cidr,proto3" json:"cidr,omitempty"`                                         //授权对象
	ChannelId     string `protobuf:"bytes,8,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`              //管道id
}

func (x *ForwardAgentActionReq) Reset() {
	*x = ForwardAgentActionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forward_secgrp_forward_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardAgentActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardAgentActionReq) ProtoMessage() {}

func (x *ForwardAgentActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_forward_secgrp_forward_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardAgentActionReq.ProtoReflect.Descriptor instead.
func (*ForwardAgentActionReq) Descriptor() ([]byte, []int) {
	return file_forward_secgrp_forward_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardAgentActionReq) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ADDRULE
}

func (x *ForwardAgentActionReq) GetRuleDirection() int32 {
	if x != nil {
		return x.RuleDirection
	}
	return 0
}

func (x *ForwardAgentActionReq) GetProtocolType() int32 {
	if x != nil {
		return x.ProtocolType
	}
	return 0
}

func (x *ForwardAgentActionReq) GetApplyPolicy() int32 {
	if x != nil {
		return x.ApplyPolicy
	}
	return 0
}

func (x *ForwardAgentActionReq) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ForwardAgentActionReq) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *ForwardAgentActionReq) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ForwardAgentActionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` //响应码
}

func (x *ForwardAgentActionResp) Reset() {
	*x = ForwardAgentActionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forward_secgrp_forward_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardAgentActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardAgentActionResp) ProtoMessage() {}

func (x *ForwardAgentActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_forward_secgrp_forward_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardAgentActionResp.ProtoReflect.Descriptor instead.
func (*ForwardAgentActionResp) Descriptor() ([]byte, []int) {
	return file_forward_secgrp_forward_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardAgentActionResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_forward_secgrp_forward_proto protoreflect.FileDescriptor

var file_forward_secgrp_forward_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2f, 0x73, 0x65, 0x63, 0x67, 0x72, 0x70,
	0x5f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x22, 0xf6, 0x01, 0x0a, 0x15, 0x46, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x27, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x75,
	0x6c, 0x65, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x72, 0x75, 0x6c, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x5f,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x70,
	0x70, 0x6c, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x69, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x64,
	0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x22, 0x2c, 0x0a, 0x16, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x2a, 0x4d,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x44, 0x44, 0x52,
	0x55, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x52,
	0x55, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x52, 0x54, 0x43, 0x49,
	0x53, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x43, 0x4f,
	0x56, 0x45, 0x52, 0x43, 0x49, 0x53, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x10, 0x03, 0x32, 0x62, 0x0a,
	0x07, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x57, 0x0a, 0x12, 0x46, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e,
	0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1f,
	0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x1b, 0x5a, 0x19, 0x6e, 0x61, 0x73, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_forward_secgrp_forward_proto_rawDescOnce sync.Once
	file_forward_secgrp_forward_proto_rawDescData = file_forward_secgrp_forward_proto_rawDesc
)

func file_forward_secgrp_forward_proto_rawDescGZIP() []byte {
	file_forward_secgrp_forward_proto_rawDescOnce.Do(func() {
		file_forward_secgrp_forward_proto_rawDescData = protoimpl.X.CompressGZIP(file_forward_secgrp_forward_proto_rawDescData)
	})
	return file_forward_secgrp_forward_proto_rawDescData
}

var file_forward_secgrp_forward_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_forward_secgrp_forward_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forward_secgrp_forward_proto_goTypes = []interface{}{
	(Action)(0),                    // 0: forward.Action
	(*ForwardAgentActionReq)(nil),  // 1: forward.ForwardAgentActionReq
	(*ForwardAgentActionResp)(nil), // 2: forward.ForwardAgentActionResp
}
var file_forward_secgrp_forward_proto_depIdxs = []int32{
	0, // 0: forward.ForwardAgentActionReq.action:type_name -> forward.Action
	1, // 1: forward.Forward.ForwardAgentAction:input_type -> forward.ForwardAgentActionReq
	2, // 2: forward.Forward.ForwardAgentAction:output_type -> forward.ForwardAgentActionResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_forward_secgrp_forward_proto_init() }
func file_forward_secgrp_forward_proto_init() {
	if File_forward_secgrp_forward_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_forward_secgrp_forward_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardAgentActionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forward_secgrp_forward_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardAgentActionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_forward_secgrp_forward_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forward_secgrp_forward_proto_goTypes,
		DependencyIndexes: file_forward_secgrp_forward_proto_depIdxs,
		EnumInfos:         file_forward_secgrp_forward_proto_enumTypes,
		MessageInfos:      file_forward_secgrp_forward_proto_msgTypes,
	}.Build()
	File_forward_secgrp_forward_proto = out.File
	file_forward_secgrp_forward_proto_rawDesc = nil
	file_forward_secgrp_forward_proto_goTypes = nil
	file_forward_secgrp_forward_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ForwardClient is the client API for Forward service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ForwardClient interface {
	//转发代理程序的行为(安全组行为/基线扫描行为)
	ForwardAgentAction(ctx context.Context, in *ForwardAgentActionReq, opts ...grpc.CallOption) (*ForwardAgentActionResp, error)
}

type forwardClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardClient(cc grpc.ClientConnInterface) ForwardClient {
	return &forwardClient{cc}
}

func (c *forwardClient) ForwardAgentAction(ctx context.Context, in *ForwardAgentActionReq, opts ...grpc.CallOption) (*ForwardAgentActionResp, error) {
	out := new(ForwardAgentActionResp)
	err := c.cc.Invoke(ctx, "/forward.Forward/ForwardAgentAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwardServer is the server API for Forward service.
type ForwardServer interface {
	//转发代理程序的行为(安全组行为/基线扫描行为)
	ForwardAgentAction(context.Context, *ForwardAgentActionReq) (*ForwardAgentActionResp, error)
}

// UnimplementedForwardServer can be embedded to have forward compatible implementations.
type UnimplementedForwardServer struct {
}

func (*UnimplementedForwardServer) ForwardAgentAction(context.Context, *ForwardAgentActionReq) (*ForwardAgentActionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardAgentAction not implemented")
}

func RegisterForwardServer(s *grpc.Server, srv ForwardServer) {
	s.RegisterService(&_Forward_serviceDesc, srv)
}

func _Forward_ForwardAgentAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardAgentActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardServer).ForwardAgentAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/forward.Forward/ForwardAgentAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardServer).ForwardAgentAction(ctx, req.(*ForwardAgentActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Forward_serviceDesc = grpc.ServiceDesc{
	ServiceName: "forward.Forward",
	HandlerType: (*ForwardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardAgentAction",
			Handler:    _Forward_ForwardAgentAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forward/secgrp_forward.proto",
}
